[server]
maxUploadSize = 40
enableCORS = false

[theme]
# צבע ראשי סגול/ויולט - נשאר קבוע בשני המצבים
primaryColor = "#9B6BFF"

# לא מגדירים צבעי רקע - נשלוט עליהם מהקוד
# backgroundColor = 
# secondaryBackgroundColor = 
# textColor = 

font = "Inter"

[client]
layout = "centered"